/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ManipulaProduto;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Produto;
import java.awt.Color;

/**
 *
 * @author Kevin
 */
public class GUIBuscaProd extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
    new Object[][]{},
    new Object[]{"Código do Produto","Nome do Produto","Quantidade","Valor de Venda"});
    
    
    
    
    
    public GUIBuscaProd() throws SQLException {
        initComponents();
        buscarProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaProd = new javax.swing.JTextField();
        cmbTipoProd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnSelecionarProd = new javax.swing.JButton();
        btnExcluirProd = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProdAlterar = new javax.swing.JTextField();
        btnSalvarAlterProd = new javax.swing.JButton();
        btnLimparProd = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Buscar e Alterar Produtos");

        txtBuscaProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBuscaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaProdKeyReleased(evt);
            }
        });

        cmbTipoProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código do Produto", "Nome do Produto", "Quantidade", "Valor de Venda", " " }));

        tblProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código do Produto", "Nome do Produto", "Quantidade", "Valor de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProd);

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar_button.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSelecionarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSelecionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/selecionar.png"))); // NOI18N
        btnSelecionarProd.setText("SELECIONAR");
        btnSelecionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarProdActionPerformed(evt);
            }
        });

        btnExcluirProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excluir.png"))); // NOI18N
        btnExcluirProd.setText("EXCLUIR");
        btnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nome do Produto:");

        txtNomeProdAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeProdAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProdAlterarKeyReleased(evt);
            }
        });

        btnSalvarAlterProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalvarAlterProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvar.png"))); // NOI18N
        btnSalvarAlterProd.setText("Salvar Alterações");
        btnSalvarAlterProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlterProdActionPerformed(evt);
            }
        });

        btnLimparProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimparProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpar.png"))); // NOI18N
        btnLimparProd.setText("Limpar");
        btnLimparProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparProdActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeProdAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSalvarAlterProd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnLimparProd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnSalvarAlterProd, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnLimparProd, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeProdAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProdAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimparProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarAlterProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(cmbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLayeredPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluirProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelecionarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnSelecionarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
try{
            buscarProd();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao buscar os dados\n"+e,
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha o catch        /
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSelecionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarProdActionPerformed
       selecionarValorProd();
    }//GEN-LAST:event_btnSelecionarProdActionPerformed

    private void btnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdActionPerformed
     excluir();
limparTabelaProd();
try{
buscarProd();
}catch(SQLException e){
    JOptionPane.showMessageDialog(rootPane, 
            "Erro ao excluir! Contate o Desenvolvedor\n"+e,
            "ERRO",
            JOptionPane.ERROR_MESSAGE);
}//fecha catch
    }//GEN-LAST:event_btnExcluirProdActionPerformed

    private void btnSalvarAlterProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlterProdActionPerformed
alterarProd();
limparTabelaProd();
try{
    buscarProd();
    
}catch(SQLException e){
    JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao alterar os dados\n"+e,
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnSalvarAlterProdActionPerformed

    private void btnLimparProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparProdActionPerformed
limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparProdActionPerformed

    private void txtBuscaProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProdKeyReleased
mudarTxt();
limparTabelaProd();
filtrarProd();
    }//GEN-LAST:event_txtBuscaProdKeyReleased

    private void txtNomeProdAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdAlterarKeyReleased
mudarTxt3();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdAlterarKeyReleased
public void buscarProd() throws SQLException{
        try{
            ManipulaProduto mp = new ManipulaProduto();
            ArrayList<Produto> alP = new ArrayList();
            alP = mp.buscarProd();
            for(int i=0; i<alP.size(); i++){
                dtm.addRow(new String[]{
                String.valueOf(alP.get(i).getCodProd()),    
                String.valueOf(alP.get(i).getNomeProd()),
                String.valueOf(alP.get(i).getQuantidade()),
                String.valueOf(alP.get(i).getValorDeVenda())
                
            });
            
            }//Fecha for
            
        
            tblProd.setModel(dtm);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro na tela de busca \n"+e,
                    "ERRO" ,
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha metodo buscar()

public void limparTabelaProd(){
        dtm.setNumRows(0);
    }

public void selecionarValorProd(){
       
        int linhaProd = tblProd.getSelectedRow();
        
       
        if(linhaProd == -1){
            JOptionPane.showMessageDialog(rootPane, 
                    "Nenhuma linha selecionada",
                    "AVISO!",
                    JOptionPane.WARNING_MESSAGE);
        }else{
           
            String codProd = (String)tblProd.getValueAt(linhaProd, 0);
            String nomeProd = (String)tblProd.getValueAt(linhaProd, 1);
            String quantidade = (String)tblProd.getValueAt(linhaProd, 2);
            String valorDeVenda = (String)tblProd.getValueAt(linhaProd, 3);
            
            txtNomeProdAlterar.setText(nomeProd);
        }
    }//Fecha o método selecionarValor()

public void excluir(){
        try{
          int linhaProd = tblProd.getSelectedRow();
        
       
        if(linhaProd == -1){
            JOptionPane.showMessageDialog(rootPane, 
                    "Nenhuma linha selecionada",
                    "AVISO!",
                    JOptionPane.WARNING_MESSAGE);
        }else{
            ManipulaProduto mp = new ManipulaProduto();
            String codProd = (String)tblProd.getValueAt(linhaProd, 0);
            
           
           int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
           if(resposta == JOptionPane.YES_OPTION){
                mp.excluir(Integer.parseInt(codProd));
               JOptionPane.showMessageDialog(rootPane, 
                   "Excluído com Sucesso",
                   "EXCLUSÃO",
                   JOptionPane.INFORMATION_MESSAGE);
           }else if(resposta == JOptionPane.NO_OPTION) {
                  JOptionPane.showMessageDialog(rootPane, 
                   "Exclusão cancelada",
                   "EXCLUSÃO",
                   JOptionPane.INFORMATION_MESSAGE);
               
           }
           
        
        
        }//fecha else
                
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane,
                            "Erro ao excluir \n"+e,
                            "ERRO",
                            JOptionPane.ERROR_MESSAGE);
                }
    }//Fecha método excluir

public void alterarProd(){
     try{
        Produto p = new Produto();
     
        p.setNomeProd(txtNomeProdAlterar.getText());
        
        ManipulaProduto mp = new ManipulaProduto();
        
        mp.alterarProd(p);
         JOptionPane.showMessageDialog(rootPane,
                 "Alterado com sucesso",
                 "Sucesso",
                 JOptionPane.INFORMATION_MESSAGE);
        
        
     }   catch(SQLException e){
         JOptionPane.showMessageDialog(rootPane,
                 "Erro ao alterar \n" +e,
                 "Erro",
                 JOptionPane.ERROR_MESSAGE);
          
    }
     
    }

public void limpar(){
        
        txtNomeProdAlterar.setText(null);
        txtBuscaProd.setText(null);
        txtBuscaProd.grabFocus();
        txtBuscaProd.setBackground(null);

        txtNomeProdAlterar.setBackground(null);
    }   

public void filtrarProd(){
        try{
            if(txtBuscaProd.getText().isEmpty()){
                buscarProd();
            }else{
                ManipulaProduto mp = new ManipulaProduto();
                String pesquisa = cmbTipoProd.getSelectedItem().toString();
                String query = null;
                if(pesquisa.equals("Código do Produto")){
                    query = "where codprod like '%"+txtBuscaProd.getText()+"%'";
                }else if(pesquisa.equals("Nome do Produto")){
                    query = "where nomeprod like '%"+txtBuscaProd.getText()+"%'";
                    }else if(pesquisa.equals("Quantidade")){
                    query = "where quantidade like '%"+txtBuscaProd.getText()+"%'";
                    
                }else{
                    query = "where valordevenda like '%"+txtBuscaProd.getText()+"%'";
                }//fecha else
            ArrayList<Produto> alP = new ArrayList();
            alP = mp.filtrarProdutos(query);
            for (int i = 0; i<alP.size(); i++) {
               dtm.addRow(new String[]{
                String.valueOf(alP.get(i).getCodProd()),alP.get(i).getNomeProd()
            }); 
            }
              tblProd.setModel(dtm);
         
         }//fecha else
        
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, 
                    "Erro ao filtrar\n" +e,
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//Fecha o método filtrar
    public void mudarTxt(){
        txtBuscaProd.setBackground(Color.GREEN);
    }

    public void mudarTxt3(){
        txtNomeProdAlterar.setBackground(Color.GREEN);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnLimparProd;
    private javax.swing.JButton btnSalvarAlterProd;
    private javax.swing.JButton btnSelecionarProd;
    private javax.swing.JComboBox<String> cmbTipoProd;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtBuscaProd;
    private javax.swing.JTextField txtNomeProdAlterar;
    // End of variables declaration//GEN-END:variables
}
