/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import Controller.ManipulaCliente;
import Model.Cliente;
import java.awt.Color;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class GUICadCli extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadCli
     */
    public GUICadCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodCli = new javax.swing.JTextField();
        txtNomeCli = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        btnCadastraCli = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtProdCom = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Código do Cliente:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Cliente:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Idade:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Telefone:");

        txtCodCli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodCliKeyReleased(evt);
            }
        });

        txtNomeCli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCliKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtIdade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdadeKeyReleased(evt);
            }
        });

        txtTel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelKeyReleased(evt);
            }
        });

        btnCadastraCli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCadastraCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastro_Button.png"))); // NOI18N
        btnCadastraCli.setText("Cadastrar Cliente");
        btnCadastraCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraCliActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Código do Produto Comprado:");

        txtProdCom.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtProdCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdComKeyReleased(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCli, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTel)
                            .addComponent(txtCodCli)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastraCli)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addComponent(txtProdCom))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastraCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraCliActionPerformed
    salvar();   
    }//GEN-LAST:event_btnCadastraCliActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCliKeyReleased
      mudarTxt();
    }//GEN-LAST:event_txtCodCliKeyReleased

    private void txtNomeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCliKeyReleased
    mudarTxt2();
    }//GEN-LAST:event_txtNomeCliKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
mudarTxt3();        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtIdadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdadeKeyReleased
mudarTxt4();        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeKeyReleased

    private void txtTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyReleased
mudarTxt5();        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyReleased

    private void txtProdComKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdComKeyReleased
mudarTxt6();        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdComKeyReleased
public void salvar(){
        Cliente c = new Cliente();
        c.setCodCli(Integer.parseInt(txtCodCli.getText()));
        c.setNomeCli(txtNomeCli.getText());
        c.setEmail(txtEmail.getText());
        c.setIdade(Integer.parseInt(txtIdade.getText()));
        c.setTelefone(txtTel.getText());
        c.setCodProdCom(Integer.parseInt(txtProdCom.getText()));
        
        ManipulaCliente mc = new ManipulaCliente();
      try{
          mc.cadastrarCli(c);
          JOptionPane.showMessageDialog(rootPane,
                  "Cliente Cadastrado",
                  "Cadastrado",
                  JOptionPane.INFORMATION_MESSAGE);
      }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane, 
                  "Erro ao cadastrar \n"+e,
                  "ERRO",
                  JOptionPane.ERROR_MESSAGE);
          System.out.println("ERRO");
      }
    }

public void limpar(){
    txtCodCli.setText(null);
    txtNomeCli.setText(null);
    txtEmail.setText(null);
    txtIdade.setText(null);
    txtTel.setText(null);
    txtProdCom.setText(null);
    txtCodCli.grabFocus();
    txtCodCli.setBackground(null);
    txtNomeCli.setBackground(null);
    txtEmail.setBackground(null);
    txtIdade.setBackground(null);
    txtTel.setBackground(null);
    txtProdCom.setBackground(null);
    
}
public void mudarTxt(){
    txtCodCli.setBackground(Color.green); 
    
}
public void mudarTxt2(){
    txtNomeCli.setBackground(Color.green); 
    
}
public void mudarTxt3(){
    txtEmail.setBackground(Color.green); 
    
}

public void mudarTxt4(){
    txtIdade.setBackground(Color.green); 
    
}

public void mudarTxt5(){
    txtTel.setBackground(Color.green); 
    
}
public void mudarTxt6(){
    txtProdCom.setBackground(Color.green); 
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraCli;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtProdCom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
