/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Controller.ManipulaProduto;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Model.Produto;
import java.awt.Color;
/**
 *
 * @author Kevin
 */
public class GUICadProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadProd
     */
    public GUICadProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodProd2 = new javax.swing.JTextField();
        txtNomeProd2 = new javax.swing.JTextField();
        txtQuant2 = new javax.swing.JTextField();
        txtValorVend2 = new javax.swing.JTextField();
        btnSalvar2 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Código do Produto:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Produto:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Quantidade:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Valor de Venda:");

        txtCodProd2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCodProd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProd2KeyReleased(evt);
            }
        });

        txtNomeProd2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeProd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProd2KeyReleased(evt);
            }
        });

        txtQuant2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuant2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuant2KeyReleased(evt);
            }
        });

        txtValorVend2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValorVend2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorVend2KeyReleased(evt);
            }
        });

        btnSalvar2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastro_Button.png"))); // NOI18N
        btnSalvar2.setText("CADASTRAR");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpar.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalvar2)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuant2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addComponent(txtNomeProd2))
                                    .addComponent(txtValorVend2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodProd2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorVend2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
       salvar2();
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
     limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodProd2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProd2KeyReleased
mudarTxt();
    }//GEN-LAST:event_txtCodProd2KeyReleased

    private void txtNomeProd2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProd2KeyReleased
mudarTxt2();
    }//GEN-LAST:event_txtNomeProd2KeyReleased

    private void txtQuant2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuant2KeyReleased
    mudarTxt3();
    }//GEN-LAST:event_txtQuant2KeyReleased

    private void txtValorVend2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorVend2KeyReleased
mudarTxt4();
    }//GEN-LAST:event_txtValorVend2KeyReleased
public void salvar2(){
        Produto p = new Produto();
        p.setCodProd(Integer.parseInt(txtCodProd2.getText()));
        p.setNomeProd(txtNomeProd2.getText());
        p.setQuantidade(Integer.parseInt(txtQuant2.getText()));
        p.setValorDeVenda(txtValorVend2.getText());
        
        ManipulaProduto mp = new ManipulaProduto();
      try{
          mp.cadastrarProd(p);
          JOptionPane.showMessageDialog(rootPane,
                  "Produto Cadastrado",
                  "Cadastrado",
                  JOptionPane.INFORMATION_MESSAGE);
      }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane, 
                  "Erro ao cadastrar \n"+e,
                  "ERRO",
                  JOptionPane.ERROR_MESSAGE);
          System.out.println("ERRO");
      }
    }

public void limpar(){
    txtCodProd2.setText(null);
    txtNomeProd2.setText(null);
    txtQuant2.setText(null);
    txtValorVend2.setText(null);
    txtCodProd2.grabFocus();
      txtCodProd2.setBackground(null); 
        txtNomeProd2.setBackground(null); 
          txtQuant2.setBackground(null); 
            txtValorVend2.setBackground(null); 
}

public void mudarTxt(){
    txtCodProd2.setBackground(Color.green); 
}

public void mudarTxt2(){
    txtNomeProd2.setBackground(Color.green); 
}
public void mudarTxt3(){
    txtQuant2.setBackground(Color.green); 
}
public void mudarTxt4(){
    txtValorVend2.setBackground(Color.green); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodProd2;
    private javax.swing.JTextField txtNomeProd2;
    private javax.swing.JTextField txtQuant2;
    private javax.swing.JTextField txtValorVend2;
    // End of variables declaration//GEN-END:variables
}
